# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-10-14 11:25:39
"""
import arcpy
from nifa2.hist_appear_constant_feature_path import hist_appear_constant_feature_path
from nifa2.hist_appear_constant_feature_path import hist_appear_constant_feature_path
from nifa2.hist_appear_constant_feature_path import hist_appear_constant_feature_path
from nifa2.hist_appear_constant_feature_path import hist_appear_constant_feature_path
from nifa2.hist_appear_constant_feature_path import hist_appear_constant_feature_path
from nifa2.hist_appear_constant_feature_path import hist_appear_constant_feature_path
from nifa2.hist_appear_constant_feature_path import hist_appear_constant_feature_path
from nifa2.hist_appear_constant_feature_path import hist_appear_constant_feature_path
from nifa2.hist_appear_constant_feature_path import hist_appear_constant_feature_path
from nifa2.hist_appear_constant_feature_path import hist_appear_constant_feature_path
from nifa2.hist_appear_constant_feature_path import hist_appear_constant_feature_path
from nifa2.hist_dataset_path import hist_dataset_path
from sys import argv

def maj_filter_premanmade(String_="Z:\\nifa\\workdir\\process\\2017\\", _2017_30m_confidence_layer_img="Z:\\nifa\\workdir\\process\\2017_30m_confidence_layer.img", CDL_2017_tif="Z:\\nifa\\workdir\\process\\2017\\CDL_2017.tif", CDL_2017_tif_2_="Z:\\nifa\\workdir\\process\\2017\\CDL_2017.tif"):  # maj_filter_premanmade

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("GeoStats")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
        String_7_ = "*082_1*"
        workdir_2_ = "Z:\\nifa\\workdir"
        Input_true_raster_or_constant_value_8_ = 82
        String_8_ = "*121_1*"
        Input_true_raster_or_constant_value_9_ = 121
        String_9_ = "*122_1*"
        Input_true_raster_or_constant_value_10_ = 122
        String_10_ = "*123_1*"
        Input_true_raster_or_constant_value_11_ = 123
        String_11_ = "*124_1*"
        Input_true_raster_or_constant_value_12_ = 124
        Roads = "Z:\\nifa\\workdir\\process\\road\\tlgdb_2017_a_us_roads.gdb\\tlgdb_2017_a_us_roads.gdb\\Roads"
        Rails = "Z:\\nifa\\workdir\\process\\road\\tlgdb_2017_a_us_rails.gdb\\tlgdb_2017_a_us_rails.gdb\\Rails"
        Input_true_raster_or_constant_value_15_ = 121
        String_6_ = "*143_1*"
        Input_true_raster_or_constant_value_6_ = 143
        String_5_ = "*142_1*"
        Input_true_raster_or_constant_value_5_ = 142
        String_4_ = "*141_1*"
        Input_true_raster_or_constant_value_4_ = 141
        String = "*111_1*"
        Input_true_raster_or_constant_value = 111
        String_2_ = "*083_1*"
        Input_true_raster_or_constant_value_2_ = 83
        String_3_ = "*063_1*"
        Input_true_raster_or_constant_value_3_ = 63
        _String_Workdir_output = f"{String_}Workdir_output"
        Input_true_raster_or_constant_value_14_ = 1
        Input_false_raster_or_constant_value_2_ = 2
        workdir = "Z:\\nifa\\workdir"
        Input_false_raster_or_constant_value = 1
        composite20190930_tif = arcpy.Raster("composite20190930.tif")

        # Process: Extract by Attributes (3) (Extract by Attributes) (sa)
        Name = "CDL_2017"
        _Name_confidence_90up_tif = fr"Z:\nifa\workdir\{Name}_confidence_90up.tif"
        Extract_by_Attributes_3_ = _Name_confidence_90up_tif
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_confidence_90up_tif = arcpy.sa.ExtractByAttributes(in_raster=_2017_30m_confidence_layer_img, where_clause="Value >= 90")
            _Name_confidence_90up_tif.save(Extract_by_Attributes_3_)


        # Process: Extract by Mask (6) (Extract by Mask) (sa)
        _Name_confidence90_tif = fr"Z:\nifa\workdir\{Name}_confidence90_.tif"
        Extract_by_Mask_6_ = _Name_confidence90_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_confidence90_tif = arcpy.sa.ExtractByMask(in_raster=CDL_2017_tif, in_mask_data=_Name_confidence_90up_tif)
            _Name_confidence90_tif.save(Extract_by_Mask_6_)


        # Process: hist_appear_constant_feature_path (7) (hist_appear_constant_feature_path) (nifa2)
        Output_Values_8_ = hist_appear_constant_feature_path(Wildcard=String_7_)[0]

        # Process: Mosaic To New Raster (13) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_082_1_tif = arcpy.management.MosaicToNewRaster(input_rasters=Output_Values_8_, output_location=workdir_2_, raster_dataset_name_with_extension=f"{Name}hist_082_1.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            _Name_hist_082_1_tif = arcpy.Raster(_Name_hist_082_1_tif)

        # Process: Con (7) (Con) (ia)
        _Name_hist_082_5up_tif = fr"Z:\nifa\workdir\{Name}_hist_082_5up.tif"
        Con_7_ = _Name_hist_082_5up_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_082_5up_tif = arcpy.ia.Con(in_conditional_raster=_Name_hist_082_1_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_8_, in_false_raster_or_constant="", where_clause="VALUE >= 1")
            _Name_hist_082_5up_tif.save(Con_7_)


        # Process: hist_appear_constant_feature_path (8) (hist_appear_constant_feature_path) (nifa2)
        Output_Values_9_ = hist_appear_constant_feature_path(Wildcard=String_8_)[0]

        # Process: Mosaic To New Raster (14) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_121_1_tif = arcpy.management.MosaicToNewRaster(input_rasters=Output_Values_9_, output_location=workdir_2_, raster_dataset_name_with_extension=f"{Name}hist_121_1.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            _Name_hist_121_1_tif = arcpy.Raster(_Name_hist_121_1_tif)

        # Process: Con (8) (Con) (ia)
        _Name_hist_121_5up_tif = fr"Z:\nifa\workdir\{Name}_hist_121_5up.tif"
        Con_8_ = _Name_hist_121_5up_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_121_5up_tif = arcpy.ia.Con(in_conditional_raster=_Name_hist_121_1_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_9_, in_false_raster_or_constant="", where_clause="VALUE >= 1")
            _Name_hist_121_5up_tif.save(Con_8_)


        # Process: hist_appear_constant_feature_path (9) (hist_appear_constant_feature_path) (nifa2)
        Output_Values_10_ = hist_appear_constant_feature_path(Wildcard=String_9_)[0]

        # Process: Mosaic To New Raster (15) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_122_1_tif = arcpy.management.MosaicToNewRaster(input_rasters=Output_Values_10_, output_location=workdir_2_, raster_dataset_name_with_extension=f"{Name}hist_122_1.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            _Name_hist_122_1_tif = arcpy.Raster(_Name_hist_122_1_tif)

        # Process: Con (9) (Con) (ia)
        _Name_hist_122_5up_tif = fr"Z:\nifa\workdir\{Name}_hist_122_5up.tif"
        Con_9_ = _Name_hist_122_5up_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_122_5up_tif = arcpy.ia.Con(in_conditional_raster=_Name_hist_122_1_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_10_, in_false_raster_or_constant="", where_clause="VALUE >= 1")
            _Name_hist_122_5up_tif.save(Con_9_)


        # Process: hist_appear_constant_feature_path (10) (hist_appear_constant_feature_path) (nifa2)
        Output_Values_11_ = hist_appear_constant_feature_path(Wildcard=String_10_)[0]

        # Process: Mosaic To New Raster (17) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_123_1_tif = arcpy.management.MosaicToNewRaster(input_rasters=Output_Values_11_, output_location=workdir_2_, raster_dataset_name_with_extension=f"{Name}hist_123_1.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            _Name_hist_123_1_tif = arcpy.Raster(_Name_hist_123_1_tif)

        # Process: Con (10) (Con) (ia)
        _Name_hist_123_5up_tif = fr"Z:\nifa\workdir\{Name}_hist_123_5up.tif"
        Con_10_ = _Name_hist_123_5up_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_123_5up_tif = arcpy.ia.Con(in_conditional_raster=_Name_hist_123_1_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_11_, in_false_raster_or_constant="", where_clause="VALUE >= 1")
            _Name_hist_123_5up_tif.save(Con_10_)


        # Process: hist_appear_constant_feature_path (11) (hist_appear_constant_feature_path) (nifa2)
        Output_Values_12_ = hist_appear_constant_feature_path(Wildcard=String_11_)[0]

        # Process: Mosaic To New Raster (18) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_124_1_tif = arcpy.management.MosaicToNewRaster(input_rasters=Output_Values_12_, output_location=workdir_2_, raster_dataset_name_with_extension=f"{Name}hist_124_1.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            _Name_hist_124_1_tif = arcpy.Raster(_Name_hist_124_1_tif)

        # Process: Con (11) (Con) (ia)
        _Name_hist_124_5up_tif = fr"Z:\nifa\workdir\{Name}_hist_124_5up.tif"
        Con_11_ = _Name_hist_124_5up_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_124_5up_tif = arcpy.ia.Con(in_conditional_raster=_Name_hist_124_1_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_12_, in_false_raster_or_constant="", where_clause="VALUE >= 1")
            _Name_hist_124_5up_tif.save(Con_11_)


        # Process: Parse Path (Parse Path) (mb)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            Path, Name, Extension, Workspace_Name = arcpy.mb.ParsePathExt(in_data_element=CDL_2017_tif, format="NOT_FORMAT")

        # Process: Feature to Raster (Feature to Raster) (conversion)
        _Name_road_tif = fr"Z:\nifa\workdir\{Name}_road.tif"
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, outputCoordinateSystem="PROJCS['Albers_Conical_Equal_Area',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Albers'],PARAMETER['false_easting',0.0],PARAMETER['false_northing',0.0],PARAMETER['central_meridian',-96.0],PARAMETER['standard_parallel_1',29.5],PARAMETER['standard_parallel_2',45.5],PARAMETER['latitude_of_origin',23.0],UNIT['Meter',1.0]]", scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", 
                              workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            arcpy.conversion.FeatureToRaster(in_features=Roads, field="MTFCC", out_raster=_Name_road_tif, cell_size="Z:\\nifa\\workdir\\process\\2021\\T14TQL_CDL_2021.tif")
            _Name_road_tif = arcpy.Raster(_Name_road_tif)

        # Process: Feature to Raster (2) (Feature to Raster) (conversion)
        _Name_rail_tif = fr"Z:\nifa\workdir\{Name}_rail.tif"
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, outputCoordinateSystem="PROJCS['Albers_Conical_Equal_Area',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Albers'],PARAMETER['false_easting',0.0],PARAMETER['false_northing',0.0],PARAMETER['central_meridian',-96.0],PARAMETER['standard_parallel_1',29.5],PARAMETER['standard_parallel_2',45.5],PARAMETER['latitude_of_origin',23.0],UNIT['Meter',1.0]]", scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", 
                              workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            arcpy.conversion.FeatureToRaster(in_features=Rails, field="MTFCC", out_raster=_Name_rail_tif, cell_size="Z:\\nifa\\workdir\\process\\2019\\CDL_2019.tif")
            _Name_rail_tif = arcpy.Raster(_Name_rail_tif)

        # Process: Mosaic To New Raster (20) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            road_rail_tif = arcpy.management.MosaicToNewRaster(input_rasters=[_Name_road_tif, _Name_rail_tif], output_location=workdir_2_, raster_dataset_name_with_extension="road_rail.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="LAST", mosaic_colormap_mode="FIRST")[0]
            road_rail_tif = arcpy.Raster(road_rail_tif)

        # Process: Extract by Mask (4) (Extract by Mask) (sa)
        _Name_extract_road_tif = fr"Z:\nifa\workdir\{Name}_extract_road__.tif"
        Extract_by_Mask_4_ = _Name_extract_road_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_extract_road_tif = arcpy.sa.ExtractByMask(in_raster=CDL_2017_tif, in_mask_data=road_rail_tif)
            _Name_extract_road_tif.save(Extract_by_Mask_4_)


        # Process: Con (12) (Con) (ia)
        _Name_extract_raod_con_tif = fr"Z:\nifa\workdir\{Name}_extract_raod_con.tif"
        Con_12_ = _Name_extract_raod_con_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_extract_raod_con_tif = arcpy.ia.Con(in_conditional_raster=_Name_extract_road_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_15_, in_false_raster_or_constant="", where_clause="")
            _Name_extract_raod_con_tif.save(Con_12_)


        # Process: hist_appear_constant_feature_path (6) (hist_appear_constant_feature_path) (nifa2)
        Output_Values_7_ = hist_appear_constant_feature_path(Wildcard=String_6_)[0]

        # Process: Mosaic To New Raster (11) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_143_1_tif = arcpy.management.MosaicToNewRaster(input_rasters=Output_Values_7_, output_location=workdir_2_, raster_dataset_name_with_extension=f"{Name}hist_143_1.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            _Name_hist_143_1_tif = arcpy.Raster(_Name_hist_143_1_tif)

        # Process: Con (6) (Con) (ia)
        _Name_hist_143_5up_tif = fr"Z:\nifa\workdir\{Name}_hist_143_5up.tif"
        Con_6_ = _Name_hist_143_5up_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_143_5up_tif = arcpy.ia.Con(in_conditional_raster=_Name_hist_143_1_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_6_, in_false_raster_or_constant="", where_clause="VALUE >= 6")
            _Name_hist_143_5up_tif.save(Con_6_)


        # Process: hist_appear_constant_feature_path (5) (hist_appear_constant_feature_path) (nifa2)
        Output_Values_6_ = hist_appear_constant_feature_path(Wildcard=String_5_)[0]

        # Process: Mosaic To New Raster (10) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_142_1_tif = arcpy.management.MosaicToNewRaster(input_rasters=Output_Values_6_, output_location=workdir_2_, raster_dataset_name_with_extension=f"{Name}hist_142_1.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            _Name_hist_142_1_tif = arcpy.Raster(_Name_hist_142_1_tif)

        # Process: Con (5) (Con) (ia)
        _Name_hist_142_5up_tif = fr"Z:\nifa\workdir\{Name}_hist_142_5up.tif"
        Con_5_ = _Name_hist_142_5up_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_142_5up_tif = arcpy.ia.Con(in_conditional_raster=_Name_hist_142_1_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_5_, in_false_raster_or_constant="", where_clause="VALUE >= 6")
            _Name_hist_142_5up_tif.save(Con_5_)


        # Process: hist_appear_constant_feature_path (4) (hist_appear_constant_feature_path) (nifa2)
        Output_Values_5_ = hist_appear_constant_feature_path(Wildcard=String_4_)[0]

        # Process: Mosaic To New Raster (9) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_141_1_tif = arcpy.management.MosaicToNewRaster(input_rasters=Output_Values_5_, output_location=workdir_2_, raster_dataset_name_with_extension=f"{Name}hist_141_1.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            _Name_hist_141_1_tif = arcpy.Raster(_Name_hist_141_1_tif)

        # Process: Con (4) (Con) (ia)
        _Name_hist_141_5up_tif = fr"Z:\nifa\workdir\{Name}_hist_141_5up.tif"
        Con_4_ = _Name_hist_141_5up_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_141_5up_tif = arcpy.ia.Con(in_conditional_raster=_Name_hist_141_1_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_4_, in_false_raster_or_constant="", where_clause="VALUE >= 6")
            _Name_hist_141_5up_tif.save(Con_4_)


        # Process: hist_appear_constant_feature_path (hist_appear_constant_feature_path) (nifa2)
        Output_Values_2_ = hist_appear_constant_feature_path(Wildcard=String)[0]

        # Process: Mosaic To New Raster (5) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_111_1_tif = arcpy.management.MosaicToNewRaster(input_rasters=Output_Values_2_, output_location=workdir_2_, raster_dataset_name_with_extension=f"{Name}hist_111_1.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            _Name_hist_111_1_tif = arcpy.Raster(_Name_hist_111_1_tif)

        # Process: Con (Con) (ia)
        _Name_hist_111_5up_tif = fr"Z:\nifa\workdir\{Name}_hist_111_5up.tif"
        Con = _Name_hist_111_5up_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_111_5up_tif = arcpy.ia.Con(in_conditional_raster=_Name_hist_111_1_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value, in_false_raster_or_constant="", where_clause="VALUE >= 6")
            _Name_hist_111_5up_tif.save(Con)


        # Process: hist_appear_constant_feature_path (2) (hist_appear_constant_feature_path) (nifa2)
        Output_Values_3_ = hist_appear_constant_feature_path(Wildcard=String_2_)[0]

        # Process: Mosaic To New Raster (7) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_083_1_tif = arcpy.management.MosaicToNewRaster(input_rasters=Output_Values_3_, output_location=workdir_2_, raster_dataset_name_with_extension=f"{Name}hist_083_1.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            _Name_hist_083_1_tif = arcpy.Raster(_Name_hist_083_1_tif)

        # Process: Con (2) (Con) (ia)
        _Name_hist_083_5up_tif = fr"Z:\nifa\workdir\{Name}_hist_083_5up.tif"
        Con_2_ = _Name_hist_083_5up_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_083_5up_tif = arcpy.ia.Con(in_conditional_raster=_Name_hist_083_1_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_2_, in_false_raster_or_constant="", where_clause="VALUE >= 6")
            _Name_hist_083_5up_tif.save(Con_2_)


        # Process: hist_appear_constant_feature_path (3) (hist_appear_constant_feature_path) (nifa2)
        Output_Values_4_ = hist_appear_constant_feature_path(Wildcard=String_3_)[0]

        # Process: Mosaic To New Raster (8) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_063_1_tif = arcpy.management.MosaicToNewRaster(input_rasters=Output_Values_4_, output_location=workdir_2_, raster_dataset_name_with_extension=f"{Name}hist_063_1.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            _Name_hist_063_1_tif = arcpy.Raster(_Name_hist_063_1_tif)

        # Process: Con (3) (Con) (ia)
        _Name_hist_063_5up_tif = fr"Z:\nifa\workdir\{Name}_hist_063_5up.tif"
        Con_3_ = _Name_hist_063_5up_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_063_5up_tif = arcpy.ia.Con(in_conditional_raster=_Name_hist_063_1_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_3_, in_false_raster_or_constant="", where_clause="VALUE >= 6")
            _Name_hist_063_5up_tif.save(Con_3_)


        # Process: Mosaic To New Raster (6) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_append_tif = arcpy.management.MosaicToNewRaster(input_rasters=[_Name_hist_143_5up_tif, _Name_hist_142_5up_tif, _Name_hist_141_5up_tif, _Name_hist_111_5up_tif, _Name_hist_083_5up_tif, _Name_hist_063_5up_tif], output_location=workdir_2_, raster_dataset_name_with_extension=f"{Name}_hist_append.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="LAST", mosaic_colormap_mode="FIRST")[0]
            _Name_hist_append_tif = arcpy.Raster(_Name_hist_append_tif)

        # Process: Set Null (2) (Set Null) (ia)
        _Name_hist_append_set_null_tif = fr"Z:\nifa\workdir\{Name}_hist_append_set_null.tif"
        Set_Null_2_ = _Name_hist_append_set_null_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_hist_append_set_null_tif = arcpy.ia.SetNull(in_conditional_raster=_Name_hist_append_tif, in_false_raster_or_constant=_Name_hist_append_tif, where_clause="VALUE = 0")
            _Name_hist_append_set_null_tif.save(Set_Null_2_)


        # Process: Mosaic To New Raster (Mosaic To New Raster) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_road_tif_299 = arcpy.management.MosaicToNewRaster(input_rasters=[_Name_extract_raod_con_tif, CDL_2017_tif], output_location=_String_Workdir_output, raster_dataset_name_with_extension=f"{Name}_road_.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="FIRST", mosaic_colormap_mode="FIRST")[0]
            _Name_road_tif_299 = arcpy.Raster(_Name_road_tif_299)

        # Process: Mosaic To New Raster (16) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_append_hist_tif = arcpy.management.MosaicToNewRaster(input_rasters=[_Name_hist_append_set_null_tif, _Name_road_tif_299], output_location=workdir_2_, raster_dataset_name_with_extension=f"{Name}_append_hist.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="FIRST", mosaic_colormap_mode="LAST")[0]
            _Name_append_hist_tif = arcpy.Raster(_Name_append_hist_tif)

        # Process: Majority Filter (4) (Majority Filter) (sa)
        _Name_maj8_pre_tif = fr"Z:\nifa\workdir\{Name}maj8_pre_.tif"
        Majority_Filter_4_ = _Name_maj8_pre_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj8_pre_tif = arcpy.sa.MajorityFilter(in_raster=_Name_append_hist_tif, number_neighbors="FOUR", majority_definition="HALF")
            _Name_maj8_pre_tif.save(Majority_Filter_4_)


        # Process: Majority Filter (Majority Filter) (sa)
        _Name_maj8_tif = fr"Z:\nifa\workdir\{Name}maj8__.tif"
        Majority_Filter = _Name_maj8_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj8_tif = arcpy.sa.MajorityFilter(in_raster=_Name_maj8_pre_tif, number_neighbors="FOUR", majority_definition="HALF")
            _Name_maj8_tif.save(Majority_Filter)


        # Process: Majority Filter (2) (Majority Filter) (sa)
        _Name_maj8sec_tif = fr"Z:\nifa\workdir\{Name}maj8sec.tif"
        Majority_Filter_2_ = _Name_maj8sec_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj8sec_tif = arcpy.sa.MajorityFilter(in_raster=_Name_maj8_tif, number_neighbors="FOUR", majority_definition="HALF")
            _Name_maj8sec_tif.save(Majority_Filter_2_)


        # Process: Majority Filter (3) (Majority Filter) (sa)
        _Name_maj83rd_tif = fr"Z:\nifa\workdir\{Name}maj83rd.tif"
        Majority_Filter_3_ = _Name_maj83rd_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_tif = arcpy.sa.MajorityFilter(in_raster=_Name_maj8sec_tif, number_neighbors="FOUR", majority_definition="HALF")
            _Name_maj83rd_tif.save(Majority_Filter_3_)


        # Process: Extract by Attributes (6) (Extract by Attributes) (sa)
        _Name_extract_is_manmade_tif = fr"Z:\nifa\workdir\{Name}_extract_is_manmade.tif"
        Extract_by_Attributes_6_ = _Name_extract_is_manmade_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_extract_is_manmade_tif = arcpy.sa.ExtractByAttributes(in_raster=_Name_maj83rd_tif, where_clause="Value = 82 Or Value = 121 Or Value = 122 Or Value = 123 Or Value = 124 Or Value = 63 Or Value = 141 Or Value = 142 Or Value = 143 Or Value = 83 Or Value = 111")
            _Name_extract_is_manmade_tif.save(Extract_by_Attributes_6_)


        # Process: Extract by Attributes (5) (Extract by Attributes) (sa)
        _Name_extract_non_manmade_tif = fr"Z:\nifa\workdir\{Name}_extract_non_manmade.tif"
        Extract_by_Attributes_5_ = _Name_extract_non_manmade_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_extract_non_manmade_tif = arcpy.sa.ExtractByAttributes(in_raster=_Name_maj83rd_tif, where_clause="Value <> 82 And Value <> 121 And Value <> 122 And Value <> 123 And Value <> 124 And Value <> 63 And Value <> 141 And Value <> 142 And Value <> 143 And Value <> 83 And Value <> 111")
            _Name_extract_non_manmade_tif.save(Extract_by_Attributes_5_)


        # Process: Region Group (Region Group) (sa)
        _Name_maj83rd_regiion_w1_tif = fr"Z:\nifa\workdir\{Name}maj83rd_regiion_w1.tif"
        Region_Group = _Name_maj83rd_regiion_w1_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_regiion_w1_tif = arcpy.sa.RegionGroup(in_raster=_Name_extract_non_manmade_tif, number_neighbors="FOUR", zone_connectivity="WITHIN", add_link="ADD_LINK", excluded_value=None)
            _Name_maj83rd_regiion_w1_tif.save(Region_Group)


        # Process: Con (13) (Con) (ia)
        _Name_maj83rd_regiion_val_cnv_w1_tif = fr"Z:\nifa\workdir\{Name}maj83rd_regiion_val_cnv_w1.tif"
        Con_13_ = _Name_maj83rd_regiion_val_cnv_w1_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_regiion_val_cnv_w1_tif = arcpy.ia.Con(in_conditional_raster=_Name_maj83rd_regiion_w1_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_14_, in_false_raster_or_constant=Input_false_raster_or_constant_value_2_, where_clause="Count = 1")
            _Name_maj83rd_regiion_val_cnv_w1_tif.save(Con_13_)


        # Process: Region Group (5) (Region Group) (sa)
        _Name_maj83rd_regiion_w2_tif = fr"Z:\nifa\workdir\{Name}maj83rd_regiion_w2.tif"
        Region_Group_5_ = _Name_maj83rd_regiion_w2_tif
        with arcpy.EnvManager(extent="-1063946.45015294 310919.600337779 33851.3081378031 2959098.47716915", scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_regiion_w2_tif = arcpy.sa.RegionGroup(in_raster=_Name_extract_non_manmade_tif, number_neighbors="FOUR", zone_connectivity="WITHIN", add_link="ADD_LINK", excluded_value=None)
            _Name_maj83rd_regiion_w2_tif.save(Region_Group_5_)


        # Process: Con (14) (Con) (ia)
        _Name_maj83rd_regiion_val_cnv_w2_tif = fr"Z:\nifa\workdir\{Name}maj83rd_regiion_val_cnv_w2.tif"
        Con_14_ = _Name_maj83rd_regiion_val_cnv_w2_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_regiion_val_cnv_w2_tif = arcpy.ia.Con(in_conditional_raster=_Name_maj83rd_regiion_w2_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_14_, in_false_raster_or_constant=Input_false_raster_or_constant_value_2_, where_clause="Count = 1")
            _Name_maj83rd_regiion_val_cnv_w2_tif.save(Con_14_)


        # Process: Region Group (6) (Region Group) (sa)
        _Name_maj83rd_regiion_e1_tif = fr"Z:\nifa\workdir\{Name}maj83rd_regiion_e1.tif"
        Region_Group_6_ = _Name_maj83rd_regiion_e1_tif
        with arcpy.EnvManager(extent="-49502.2202949735 591000.651255151 1097388.33239014 2930681.37549007", scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_regiion_e1_tif = arcpy.sa.RegionGroup(in_raster=_Name_extract_non_manmade_tif, number_neighbors="FOUR", zone_connectivity="WITHIN", add_link="ADD_LINK", excluded_value=None)
            _Name_maj83rd_regiion_e1_tif.save(Region_Group_6_)


        # Process: Con (15) (Con) (ia)
        _Name_maj83rd_regiion_val_cnv_e1_tif = fr"Z:\nifa\workdir\{Name}maj83rd_regiion_val_cnv_e1.tif"
        Con_15_ = _Name_maj83rd_regiion_val_cnv_e1_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_regiion_val_cnv_e1_tif = arcpy.ia.Con(in_conditional_raster=_Name_maj83rd_regiion_e1_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_14_, in_false_raster_or_constant=Input_false_raster_or_constant_value_2_, where_clause="Count = 1")
            _Name_maj83rd_regiion_val_cnv_e1_tif.save(Con_15_)


        # Process: Region Group (7) (Region Group) (sa)
        _Name_maj83rd_regiion_e2_tif = fr"Z:\nifa\workdir\{Name}maj83rd_regiion_e2.tif"
        Region_Group_7_ = _Name_maj83rd_regiion_e2_tif
        with arcpy.EnvManager(extent="1040091.96324117 276935.312291291 2258208.84005527 3013008.64167383", scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_regiion_e2_tif = arcpy.sa.RegionGroup(in_raster=_Name_extract_non_manmade_tif, number_neighbors="FOUR", zone_connectivity="WITHIN", add_link="ADD_LINK", excluded_value=None)
            _Name_maj83rd_regiion_e2_tif.save(Region_Group_7_)


        # Process: Con (16) (Con) (ia)
        _Name_maj83rd_regiion_val_cnv_e2_tif = fr"Z:\nifa\workdir\{Name}maj83rd_regiion_val_cnv_e2.tif"
        Con_16_ = _Name_maj83rd_regiion_val_cnv_e2_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_regiion_val_cnv_e2_tif = arcpy.ia.Con(in_conditional_raster=_Name_maj83rd_regiion_e2_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value_14_, in_false_raster_or_constant=Input_false_raster_or_constant_value_2_, where_clause="Count = 1")
            _Name_maj83rd_regiion_val_cnv_e2_tif.save(Con_16_)


        # Process: Mosaic To New Raster (22) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_regiion_con_mosaic_tif = arcpy.management.MosaicToNewRaster(input_rasters=[_Name_maj83rd_regiion_val_cnv_w1_tif, _Name_maj83rd_regiion_val_cnv_w2_tif, _Name_maj83rd_regiion_val_cnv_e1_tif, _Name_maj83rd_regiion_val_cnv_e2_tif], output_location=workdir, raster_dataset_name_with_extension=f"{Name}maj83rd_regiion_con_mosaic.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="LAST", mosaic_colormap_mode="FIRST")[0]
            _Name_maj83rd_regiion_con_mosaic_tif = arcpy.Raster(_Name_maj83rd_regiion_con_mosaic_tif)

        # Process: Mosaic To New Raster (19) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_extract_is_manmade_region_mosaic_tif = arcpy.management.MosaicToNewRaster(input_rasters=[_Name_extract_is_manmade_tif, _Name_maj83rd_regiion_val_cnv_w1_tif, _Name_maj83rd_regiion_con_mosaic_tif], output_location=workdir, raster_dataset_name_with_extension=f"{Name}_extract_is_manmade_region_mosaic.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="LAST", mosaic_colormap_mode="FIRST")[0]
            _Name_extract_is_manmade_region_mosaic_tif = arcpy.Raster(_Name_extract_is_manmade_region_mosaic_tif)

        # Process: Set Null (Set Null) (ia)
        _Name_maj83rd_region_null_tif = fr"Z:\nifa\workdir\{Name}maj83rd_region_null.tif"
        Set_Null = _Name_maj83rd_region_null_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_region_null_tif = arcpy.ia.SetNull(in_conditional_raster=_Name_extract_is_manmade_region_mosaic_tif, in_false_raster_or_constant=Input_false_raster_or_constant_value, where_clause="VALUE = 1")
            _Name_maj83rd_region_null_tif.save(Set_Null)


        # Process: Nibble (Nibble) (sa)
        _Name_maj83rd_region_null_nibble_w1_tif = fr"Z:\nifa\workdir\{Name}maj83rd_region_null_nibble_w1.tif"
        Nibble = _Name_maj83rd_region_null_nibble_w1_tif
        with arcpy.EnvManager(extent="-2356069.52578692 991812.881485563 -905283.323954564 3172576.65456275", scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_region_null_nibble_w1_tif = arcpy.sa.Nibble(in_raster=_Name_maj83rd_tif, in_mask_raster=_Name_maj83rd_region_null_tif, nibble_values="DATA_ONLY", nibble_nodata="PRESERVE_NODATA", in_zone_raster="")
            _Name_maj83rd_region_null_nibble_w1_tif.save(Nibble)


        # Process: Nibble (4) (Nibble) (sa)
        _Name_maj83rd_region_null_nibble_w2_tif = fr"Z:\nifa\workdir\{Name}maj83rd_region_null_nibble_w2.tif"
        Nibble_4_ = _Name_maj83rd_region_null_nibble_w2_tif
        with arcpy.EnvManager(extent="-1063946.45015294 310919.600337779 33851.3081378031 2959098.47716915", scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_region_null_nibble_w2_tif = arcpy.sa.Nibble(in_raster=_Name_maj83rd_tif, in_mask_raster=_Name_maj83rd_region_null_tif, nibble_values="DATA_ONLY", nibble_nodata="PRESERVE_NODATA", in_zone_raster="")
            _Name_maj83rd_region_null_nibble_w2_tif.save(Nibble_4_)


        # Process: Nibble (5) (Nibble) (sa)
        _Name_maj83rd_region_null_nibble_e1_tif = fr"Z:\nifa\workdir\{Name}maj83rd_region_null_nibble_e1.tif"
        Nibble_5_ = _Name_maj83rd_region_null_nibble_e1_tif
        with arcpy.EnvManager(extent="-49502.2202949735 591000.651255151 1097388.33239014 2930681.37549007", scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_region_null_nibble_e1_tif = arcpy.sa.Nibble(in_raster=_Name_maj83rd_tif, in_mask_raster=_Name_maj83rd_region_null_tif, nibble_values="DATA_ONLY", nibble_nodata="PRESERVE_NODATA", in_zone_raster="")
            _Name_maj83rd_region_null_nibble_e1_tif.save(Nibble_5_)


        # Process: Nibble (6) (Nibble) (sa)
        _Name_maj83rd_region_null_nibble_e2_tif = fr"Z:\nifa\workdir\{Name}maj83rd_region_null_nibble_e2.tif"
        Nibble_6_ = _Name_maj83rd_region_null_nibble_e2_tif
        with arcpy.EnvManager(extent="1040091.96324117 276935.312291291 2258208.84005527 3013008.64167383", scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_maj83rd_region_null_nibble_e2_tif = arcpy.sa.Nibble(in_raster=_Name_maj83rd_tif, in_mask_raster=_Name_maj83rd_region_null_tif, nibble_values="DATA_ONLY", nibble_nodata="PRESERVE_NODATA", in_zone_raster="")
            _Name_maj83rd_region_null_nibble_e2_tif.save(Nibble_6_)


        # Process: Mosaic To New Raster (21) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_nibble_mosaic_tif = arcpy.management.MosaicToNewRaster(input_rasters=[_Name_maj83rd_region_null_nibble_w1_tif, _Name_maj83rd_region_null_nibble_w2_tif, _Name_maj83rd_region_null_nibble_e1_tif, _Name_maj83rd_region_null_nibble_e2_tif], output_location=workdir, raster_dataset_name_with_extension=f"{Name}_nibble_mosaic.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="LAST", mosaic_colormap_mode="FIRST")[0]
            _Name_nibble_mosaic_tif = arcpy.Raster(_Name_nibble_mosaic_tif)

        # Process: Minus (Minus) (3d)
        _Name_maj8sec_minus_orig_tif = fr"Z:\nifa\workdir\{Name}maj8sec_minus_orig.tif"
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            arcpy.ddd.Minus(in_raster_or_constant1=_Name_nibble_mosaic_tif, in_raster_or_constant2=_Name_append_hist_tif, out_raster=_Name_maj8sec_minus_orig_tif)
            _Name_maj8sec_minus_orig_tif = arcpy.Raster(_Name_maj8sec_minus_orig_tif)

        # Process: Extract by Attributes (Extract by Attributes) (sa)
        _Name_changing_pixel_tif = fr"Z:\nifa\workdir\{Name}changing_pixel.tif"
        Extract_by_Attributes = _Name_changing_pixel_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_changing_pixel_tif = arcpy.sa.ExtractByAttributes(in_raster=_Name_maj8sec_minus_orig_tif, where_clause="VALUE <> 0")
            _Name_changing_pixel_tif.save(Extract_by_Attributes)


        # Process: hist_dataset_path (hist_dataset_path) (nifa2)
        Output_Values = hist_dataset_path()[0]

        # Process: Mosaic To New Raster (4) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(extent=CDL_2017_tif_2_, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_historical_data_tif = arcpy.management.MosaicToNewRaster(input_rasters=Output_Values, output_location=workdir, raster_dataset_name_with_extension=f"{Name}_historical_data.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="SUM", mosaic_colormap_mode="FIRST")[0]
            _Name_historical_data_tif = arcpy.Raster(_Name_historical_data_tif)

        # Process: Extract by Attributes (2) (Extract by Attributes) (sa)
        _Name_Historical_Mosaic_2009_19_7up_tif = fr"Z:\nifa\workdir\{Name}_Historical_Mosaic_2009_19_7up.tif"
        Extract_by_Attributes_2_ = _Name_Historical_Mosaic_2009_19_7up_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_Historical_Mosaic_2009_19_7up_tif = arcpy.sa.ExtractByAttributes(in_raster=_Name_historical_data_tif, where_clause="VALUE >= 6")
            _Name_Historical_Mosaic_2009_19_7up_tif.save(Extract_by_Attributes_2_)


        # Process: Extract by Mask (3) (Extract by Mask) (sa)
        _Name_changingpixel_extract7up_tif = fr"Z:\nifa\workdir\{Name}changingpixel_extract7up.tif"
        Extract_by_Mask_3_ = _Name_changingpixel_extract7up_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_changingpixel_extract7up_tif = arcpy.sa.ExtractByMask(in_raster=_Name_changing_pixel_tif, in_mask_data=_Name_Historical_Mosaic_2009_19_7up_tif)
            _Name_changingpixel_extract7up_tif.save(Extract_by_Mask_3_)


        # Process: Extract by Mask (Extract by Mask) (sa)
        _Name_changingpixel_extract7up_extract_tif = fr"Z:\nifa\workdir\{Name}changingpixel_extract7up_extract.tif"
        Extract_by_Mask = _Name_changingpixel_extract7up_extract_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_changingpixel_extract7up_extract_tif = arcpy.sa.ExtractByMask(in_raster=CDL_2017_tif, in_mask_data=_Name_changingpixel_extract7up_tif)
            _Name_changingpixel_extract7up_extract_tif.save(Extract_by_Mask)


        # Process: Mosaic To New Raster (2) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_majfilter_historical_same_tif = arcpy.management.MosaicToNewRaster(input_rasters=[_Name_changingpixel_extract7up_extract_tif, _Name_nibble_mosaic_tif], output_location=workdir, raster_dataset_name_with_extension=f"{Name}majfilter_historical_same.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="FIRST", mosaic_colormap_mode="FIRST")[0]
            _Name_majfilter_historical_same_tif = arcpy.Raster(_Name_majfilter_historical_same_tif)

        # Process: Mosaic To New Raster (3) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_majfilter_historical_same_add_conf_tif = arcpy.management.MosaicToNewRaster(input_rasters=[_Name_majfilter_historical_same_tif], output_location=workdir, raster_dataset_name_with_extension=f"{Name}majfilter_historical_same_add_conf.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="FIRST", mosaic_colormap_mode="FIRST")[0]
            _Name_majfilter_historical_same_add_conf_tif = arcpy.Raster(_Name_majfilter_historical_same_add_conf_tif)

        # Process: Mosaic To New Raster (12) (Mosaic To New Raster) (management)
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_new_8yrs_4_half_tif = arcpy.management.MosaicToNewRaster(input_rasters=[_Name_extract_raod_con_tif, _Name_majfilter_historical_same_add_conf_tif], output_location=_String_Workdir_output, raster_dataset_name_with_extension=f"{Name}_new_8yrs_4_half.tif", coordinate_system_for_the_raster="", pixel_type="8_BIT_UNSIGNED", cellsize=None, number_of_bands=1, mosaic_method="FIRST", mosaic_colormap_mode="FIRST")[0]
            _Name_new_8yrs_4_half_tif = arcpy.Raster(_Name_new_8yrs_4_half_tif)

        # Process: Diff (Diff) (ia)
        _Name_Diff_tif = fr"Z:\nifa\workdir\{Name}Diff.tif"
        Diff = _Name_Diff_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_Diff_tif = arcpy.ia.Diff(in_raster_or_constant1=_Name_new_8yrs_4_half_tif, in_raster_or_constant2=CDL_2017_tif)
            _Name_Diff_tif.save(Diff)


        # Process: Extract by Attributes (4) (Extract by Attributes) (sa)
        _Name_changed_aoi_no0_tif = fr"Z:\nifa\workdir\process\2019\compare\{Name}_changed_aoi_no0.tif"
        Extract_by_Attributes_4_ = _Name_changed_aoi_no0_tif
        with arcpy.EnvManager(extent=composite20190930_tif, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_changed_aoi_no0_tif = arcpy.sa.ExtractByAttributes(in_raster=_Name_Diff_tif, where_clause="Value <> 0")
            _Name_changed_aoi_no0_tif.save(Extract_by_Attributes_4_)


        # Process: Raster to Point (Raster to Point) (conversion)
        _Name_changed_aoi_no0_shp = fr"Z:\nifa\workdir\process\2019\compare\{Name}_changed_aoi_no0.shp"
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            arcpy.conversion.RasterToPoint(in_raster=_Name_changed_aoi_no0_tif, out_point_features=_Name_changed_aoi_no0_shp, raster_field="VALUE")

        # Process: Subset Features (Subset Features) (ga)
        _Name_changed_aoi_no0_train_shp = fr"Z:\nifa\workdir\process\2019\compare\{Name}_changed_aoi_no0_train.shp"
        _Name_changed_aoi_no0_test_shp = fr"Z:\nifa\workdir\process\2019\compare\{Name}_changed_aoi_no0_test.shp"
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            arcpy.ga.SubsetFeatures(in_features=_Name_changed_aoi_no0_shp, out_training_feature_class=_Name_changed_aoi_no0_train_shp, out_test_feature_class=_Name_changed_aoi_no0_test_shp, size_of_training_dataset=200, subset_size_units="ABSOLUTE_VALUE")

        # Process: Extract Values to Points (Extract Values to Points) (sa)
        _Name_changed_aoi_no0_train_shp_350 = fr"Z:\nifa\workdir\process\2019\compare\{Name}_changed_aoi_no0_train_.shp"
        with arcpy.EnvManager(extent=composite20190930_tif, scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            arcpy.sa.ExtractValuesToPoints(in_point_features=_Name_changed_aoi_no0_train_shp, in_raster=CDL_2017_tif, out_point_features=_Name_changed_aoi_no0_train_shp_350, interpolate_values="NONE", add_attributes="VALUE_ONLY")

        # Process: Extract by Attributes (7) (Extract by Attributes) (sa)
        _Name_new_8yrs_corn_soy_tif = fr"Z:\nifa\workdir\process\2019\compare\{Name}_new_8yrs_corn_soy.tif"
        Extract_by_Attributes_7_ = _Name_new_8yrs_corn_soy_tif
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            _Name_new_8yrs_corn_soy_tif = arcpy.sa.ExtractByAttributes(in_raster=_Name_new_8yrs_4_half_tif, where_clause="Value = 1 Or Value = 5")
            _Name_new_8yrs_corn_soy_tif.save(Extract_by_Attributes_7_)


        # Process: Tabulate Area (Tabulate Area) (sa)
        Tabulat_Name_ = fr"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb\Tabulat_{Name}"
        with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
            arcpy.sa.TabulateArea(in_zone_data=_Name_new_8yrs_corn_soy_tif, zone_field="VALUE", in_class_data=CDL_2017_tif_2_, class_field="FIPS", out_table=Tabulat_Name_, processing_cell_size="Z:\\nifa\\workdir\\process\\2019\\compare\\CDL_2019_31_new_8yrs_corn_soy.tif", classes_as_rows="CLASSES_AS_FIELDS")
            .save(Tabulate_Area)


if __name__ == '__main__':
    maj_filter_premanmade(*argv[1:])
