# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-10-14 11:26:38
"""
import arcpy
from sys import argv
def #  NOT  IMPLEMENTED# Function Body not implemented

def hist_dataset_path():  # hist_dataset_path

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
        hist_freq = "Z:\\nifa\\workdir\\process\\2017\\hist_freq"

        for Raster, Name in #  NOT  IMPLEMENTED(hist_freq, "", "", "NOT_RECURSIVE"):

            # Process: Collect_Values (Collect Values) 
            # Collect Values Utility is not implemented 

            return Output_Values

if __name__ == '__main__':
    hist_dataset_path(*argv[1:])
