# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-10-14 11:26:17
"""
import arcpy
from sys import argv
def #  NOT  IMPLEMENTED# Function Body not implemented

def hist_appear(_Name_minusby2019_Con_0to1_tif=fr"{String}hist_freq\{Name}minusby2019_Con_0to1.tif", CDL_2017_tif="Z:\\nifa\\workdir\\process\\2017\\CDL_2017.tif", String="Z:\\nifa\\workdir\\process\\2017\\"):  # hist_appear

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
        _String_hist = f"{String}hist"
        Input_true_raster_or_constant_value = 1
        Input_false_raster_or_constant_value = 0

        for CDL_2009_31109_tif, Name in #  NOT  IMPLEMENTED(_String_hist, "", "", "NOT_RECURSIVE"):

            # Process: Minus (Minus) (ia)
            Name = "CDL_2016.tif"
            _Name_minusby2019_tif = fr"Z:\nifa\workdir\{Name}minusby2019.tif"
            Minus = _Name_minusby2019_tif
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
                _Name_minusby2019_tif = arcpy.ia.Minus(in_raster_or_constant1=CDL_2017_tif, in_raster_or_constant2=CDL_2009_31109_tif)
                _Name_minusby2019_tif.save(Minus)


            # Process: Con (Con) (ia)
            Con = _Name_minusby2019_Con_0to1_tif
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
                _Name_minusby2019_Con_0to1_tif = arcpy.ia.Con(in_conditional_raster=_Name_minusby2019_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value, in_false_raster_or_constant=Input_false_raster_or_constant_value, where_clause="Value = 0")
                _Name_minusby2019_Con_0to1_tif.save(Con)


if __name__ == '__main__':
    hist_appear(*argv[1:])
