# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-10-14 11:27:01
"""
import arcpy
from sys import argv
def #  NOT  IMPLEMENTED# Function Body not implemented

def hist_appear_constant_feature(String="Z:\\nifa\\workdir\\process\\2017\\"):  # hist_appear_constant_feature

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
        _String_hist = f"{String}hist"
        Input_true_raster_or_constant_value = 1
        Input_false_raster_or_constant_value = 0

        for CDL_2009_31109_tif, Name in #  NOT  IMPLEMENTED(_String_hist, "", "", "NOT_RECURSIVE"):

            # Process: Con (Con) (ia)
            Name = "CDL_2016.tif"
            _Name_111_1_tif = fr"{String}hist_const_freq\{Name}111_1.tif"
            Con = _Name_111_1_tif
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
                _Name_111_1_tif = arcpy.ia.Con(in_conditional_raster=CDL_2009_31109_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value, in_false_raster_or_constant=Input_false_raster_or_constant_value, where_clause="VALUE = 111")
                _Name_111_1_tif.save(Con)


            # Process: Con (2) (Con) (ia)
            _Name_083_1_tif = fr"{String}hist_const_freq\{Name}083_1.tif"
            Con_2_ = _Name_083_1_tif
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
                _Name_083_1_tif = arcpy.ia.Con(in_conditional_raster=CDL_2009_31109_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value, in_false_raster_or_constant=Input_false_raster_or_constant_value, where_clause="VALUE = 83")
                _Name_083_1_tif.save(Con_2_)


            # Process: Con (3) (Con) (ia)
            _Name_063_1_tif = fr"{String}hist_const_freq\{Name}063_1.tif"
            Con_3_ = _Name_063_1_tif
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
                _Name_063_1_tif = arcpy.ia.Con(in_conditional_raster=CDL_2009_31109_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value, in_false_raster_or_constant=Input_false_raster_or_constant_value, where_clause="VALUE = 63")
                _Name_063_1_tif.save(Con_3_)


            # Process: Con (4) (Con) (ia)
            _Name_141_1_tif = fr"{String}hist_const_freq\{Name}141_1.tif"
            Con_4_ = _Name_141_1_tif
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
                _Name_141_1_tif = arcpy.ia.Con(in_conditional_raster=CDL_2009_31109_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value, in_false_raster_or_constant=Input_false_raster_or_constant_value, where_clause="VALUE = 141")
                _Name_141_1_tif.save(Con_4_)


            # Process: Con (5) (Con) (ia)
            _Name_142_1_tif = fr"{String}hist_const_freq\{Name}142_1.tif"
            Con_5_ = _Name_142_1_tif
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
                _Name_142_1_tif = arcpy.ia.Con(in_conditional_raster=CDL_2009_31109_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value, in_false_raster_or_constant=Input_false_raster_or_constant_value, where_clause="VALUE = 142")
                _Name_142_1_tif.save(Con_5_)


            # Process: Con (6) (Con) (ia)
            _Name_143_1_tif = fr"{String}hist_const_freq\{Name}143_1.tif"
            Con_6_ = _Name_143_1_tif
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
                _Name_143_1_tif = arcpy.ia.Con(in_conditional_raster=CDL_2009_31109_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value, in_false_raster_or_constant=Input_false_raster_or_constant_value, where_clause="VALUE = 143")
                _Name_143_1_tif.save(Con_6_)


            # Process: Con (7) (Con) (ia)
            _Name_123_1_tif = fr"{String}hist_const_freq\{Name}123_1.tif"
            Con_7_ = _Name_123_1_tif
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
                _Name_123_1_tif = arcpy.ia.Con(in_conditional_raster=CDL_2009_31109_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value, in_false_raster_or_constant=Input_false_raster_or_constant_value, where_clause="VALUE = 123")
                _Name_123_1_tif.save(Con_7_)


            # Process: Con (8) (Con) (ia)
            _Name_122_1_tif = fr"{String}hist_const_freq\{Name}122_1.tif"
            Con_8_ = _Name_122_1_tif
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
                _Name_122_1_tif = arcpy.ia.Con(in_conditional_raster=CDL_2009_31109_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value, in_false_raster_or_constant=Input_false_raster_or_constant_value, where_clause="VALUE = 122")
                _Name_122_1_tif.save(Con_8_)


            # Process: Con (9) (Con) (ia)
            _Name_121_1_tif = fr"{String}hist_const_freq\{Name}121_1.tif"
            Con_9_ = _Name_121_1_tif
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
                _Name_121_1_tif = arcpy.ia.Con(in_conditional_raster=CDL_2009_31109_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value, in_false_raster_or_constant=Input_false_raster_or_constant_value, where_clause="VALUE = 121")
                _Name_121_1_tif.save(Con_9_)


            # Process: Con (10) (Con) (ia)
            _Name_082_1_tif = fr"{String}hist_const_freq\{Name}082_1.tif"
            Con_10_ = _Name_082_1_tif
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
                _Name_082_1_tif = arcpy.ia.Con(in_conditional_raster=CDL_2009_31109_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value, in_false_raster_or_constant=Input_false_raster_or_constant_value, where_clause="VALUE = 82")
                _Name_082_1_tif.save(Con_10_)


            # Process: Con (11) (Con) (ia)
            _Name_124_1_tif = fr"{String}hist_const_freq\{Name}124_1.tif"
            Con_11_ = _Name_124_1_tif
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb", workspace=r"C:\Users\linli_home\Documents\ArcGIS\Projects\nifa2\nifa2.gdb"):
                _Name_124_1_tif = arcpy.ia.Con(in_conditional_raster=CDL_2009_31109_tif, in_true_raster_or_constant=Input_true_raster_or_constant_value, in_false_raster_or_constant=Input_false_raster_or_constant_value, where_clause="VALUE = 124")
                _Name_124_1_tif.save(Con_11_)


if __name__ == '__main__':
    hist_appear_constant_feature(*argv[1:])
